'use strict';
const $=id=>document.getElementById(id);
const names={dubai_oil:'두바이유 (USD/배럴)',usd_krw:'원/달러 (원/USD)',bond_3y:'국고채 3년 (연%)',gasoline:'휘발유 (원/L)',gold_usd:'국제 금 (USD/oz)',kospi:'KOSPI (지수)'};
let DATA;
function pearson(a,b){const n=a.length;if(n<3)return null;const ma=a.reduce((s,v)=>s+v,0)/n,mb=b.reduce((s,v)=>s+v,0)/n;let cov=0,va=0,vb=0;for(let i=0;i<n;i++){cov+=(a[i]-ma)*(b[i]-mb);va+=(a[i]-ma)**2;vb+=(b[i]-mb)**2;}return va&&vb?cov/Math.sqrt(va*vb):null;}
function chart(id,series,labels,fixed=null){const el=$(id),W=el.viewBox.baseVal.width,H=el.viewBox.baseVal.height,L=65,R=20,T=25,B=45;const vals=series.flatMap(s=>s.values).filter(Number.isFinite);if(!vals.length){el.innerHTML='<text x="65" y="90">계산할 수 있는 값이 없습니다</text>';return;}let lo=fixed?fixed[0]:Math.min(...vals),hi=fixed?fixed[1]:Math.max(...vals);if(lo===hi){lo-=1;hi+=1;}let html='';for(let t=0;t<5;t++){const y=T+(H-T-B)*t/4;const v=hi-(hi-lo)*t/4;html+=`<line x1="${L}" y1="${y}" x2="${W-R}" y2="${y}" stroke="#e5edf3"/><text x="${L-8}" y="${y+4}" text-anchor="end" fill="#526477" font-size="12">${v.toFixed(Math.max(Math.abs(hi),Math.abs(lo))<10?2:0)}</text>`;}for(const s of series){let path='',open=false;s.values.forEach((v,i)=>{if(!Number.isFinite(v)){open=false;return;}const x=L+(W-L-R)*i/Math.max(1,s.values.length-1),y=T+(hi-v)/(hi-lo)*(H-T-B);path+=`${open?'L':'M'}${x.toFixed(2)},${y.toFixed(2)} `;open=true;});html+=`<path d="${path}" fill="none" stroke="${s.color}" stroke-width="2"/>`;}[0,Math.floor((labels.length-1)/2),labels.length-1].forEach((i,j)=>{if(i<0)return;const x=L+(W-L-R)*i/Math.max(1,labels.length-1);html+=`<text x="${x}" y="${H-10}" text-anchor="${j===0?'start':j===2?'end':'middle'}" fill="#526477" font-size="12">${labels[i]}</text>`;});el.innerHTML=html;}
function change(rows,i,k){if(i===0)return null;return k==='bond_3y'?rows[i][k]-rows[i-1][k]:(rows[i][k]/rows[i-1][k]-1)*100;}
function update(){const start=$('start').value,end=$('end').value;const rows=DATA.weekly.filter(r=>r.week>=start&&r.week<=end);$('error').textContent=start>end?'시작일은 종료일보다 앞이어야 합니다':rows.length<3?'분석에는 3주 이상 선택하세요':'';if(start>end||rows.length<3){['trend','lag'].forEach(id=>$(id).innerHTML='');$('corr').innerHTML='';$('lagSummary').textContent='계산 불가';$('coverage').textContent='';return;}const k=$('metric').value,kind=$('kind').value;const value=(i,key)=>kind==='level'?rows[i][key]:change(rows,i,key);const unit=kind==='level'?names[k]:k==='bond_3y'?'금리 변화 (%p)':'주간 변화율 (%)';$('trendTitle').textContent=unit;$('coverage').textContent=`${rows[0].week} ~ ${rows.at(-1).week} · ${rows.length}주 · 관측일 수 ${Math.min(...rows.map(r=>r[k+'_obs_days']))}~${Math.max(...rows.map(r=>r[k+'_obs_days']))}일`;
chart('trend',[{values:rows.map((_,i)=>value(i,k)),color:'#176c8c'}],rows.map(r=>r.week));const lagValues=[];let best=null;for(let lag=0;lag<=12;lag++){const a=[],b=[];for(let i=lag;i<rows.length;i++){const x=value(i-lag,'dubai_oil'),y=value(i,'gasoline');if(Number.isFinite(x)&&Number.isFinite(y)){a.push(x);b.push(y);}}const r=a.length>=20?pearson(a,b):null;lagValues.push(r);if(r!==null&&(!best||r>best.r))best={lag,r,n:a.length};}$('lagSummary').textContent=best?`${best.lag}주 · r=${best.r.toFixed(3)} · n=${best.n}`:'표본 부족 (시차별 최소 20개)';chart('lag',[{values:lagValues,color:'#176c8c'}],Array.from({length:13},(_,i)=>String(i)),[-1,1]);
const pairs=[['usd_krw','gold_usd','환율·금'],['usd_krw','kospi','환율·KOSPI'],['bond_3y','kospi','금리·KOSPI']];$('corr').innerHTML=pairs.map(([x,y,label])=>{const a=[],b=[];rows.forEach((_,i)=>{const vx=value(i,x),vy=value(i,y);if(Number.isFinite(vx)&&Number.isFinite(vy)){a.push(vx);b.push(vy);}});const r=pearson(a,b);return `<tr><td>${label}</td><td>${r===null?'계산 불가':r.toFixed(3)}</td><td>${a.length}</td></tr>`;}).join('');$('interpretation').textContent='전체 기간의 관계를 매년·매주에 그대로 적용할 수 없습니다. 특히 수준과 변화의 관계를 구분해 살펴보세요.';}
function period(){const p=$('period').value;if(p==='custom')return;$('start').value=p==='all'?DATA.weekly[0].week:`${p}-01-01`;$('end').value=p==='all'?DATA.weekly.at(-1).week:`${p}-12-31`;update();}
fetch('data.json').then(r=>{if(!r.ok)throw Error('data.json을 만들려면 python scripts/build_dashboard.py를 실행하세요.');return r.json();}).then(data=>{DATA=data;period();['metric','kind'].forEach(id=>$(id).addEventListener('change',update));$('period').addEventListener('change',period);['start','end'].forEach(id=>$(id).addEventListener('change',()=>{$('period').value='custom';update();}));$('reset').addEventListener('click',()=>{$('period').value='all';$('metric').value='dubai_oil';$('kind').value='change';period();});const test=DATA.forecast.filter(r=>r.split==='test');const mae=key=>test.reduce((s,r)=>s+Math.abs(r.actual-r[key]),0)/test.length;$('forecastSummary').textContent=`2025년 검증 MAE로 선택: ${DATA.metadata.selected_model} · 2026년 ${test.length}주 평가 MAE ${mae('selected').toFixed(2)}원/L (직전 값 유지 ${mae('persistence').toFixed(2)}원/L)`;chart('forecast',[{values:test.map(r=>r.actual),color:'#176c8c'},{values:test.map(r=>r.selected),color:'#e38832'},{values:test.map(r=>r.persistence),color:'#8797a6'}],test.map(r=>r.target_week));}).catch(e=>{$('error').textContent=e.message;});
